### ISSUE TITLE
Missing direct dependency

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Calendar#11]
In this file: https://github.com/Sylius/Calendar/blob/main/config/services_test.yaml you define services that use Behat, but Behat is only a dev requirement. Therefore an application not using Behat will throw an exception like this when run in `test` env:

```
Invalid service "Sylius\Calendar\Tests\Behat\Context\Domain\CalendarContext": class "Behat\Behat\Context\Context" not found while loading "Sylius\Calendar\Tests\Behat\Context\Domain\CalendarContext".
```

I guess it's not the correct solution to move Behat to direct dependencies. Instead those test services should only be enabled if Behat is actually installed or some other solution?

**Comment by GSadee** [comment]
Hi Joachim, sorry for the late reply and thank you for reporting the problem. 
I agree with you that we should not force the installation of Behat, that is only a dev requirement. We will try to improve this in the next version of this package. But of course, if you have the opportunity to submit a PR with a solution, then feel free to do so 😃
